<?php
/**
 * @var \Study\Team\Block\Team $block
 */
?>



<div class="modal fade" id="create" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Add new team</h5>
            </div>
            <div>
                <form action="/team/index/save" method="GET""
                    <div class="form-group">
                        <small>Name</small>
                        <input type="text" name="name" class="form-control">
                    </div>
                    <div class="form-group">
                        <small>country</small>
                        <input type="text" name="country" class="form-control">
                    </div>
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Save team</button>
                </form>
            </div>
        </div>
    </div>
</div>

