<?php
/**
 * @var \Study\Team\Block\Team $block
 */
$team = $block->getOneTeam();
?>

<div class="modal fade" id="edit" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5><?php echo __('Edit team');?></h5>
            </div>
            <div>
                <form action="<?php echo $block->getUrl('*/*/update'); ?>" method="GET"
                <div class="form-group">
                    <small><?php echo __('id');?></small>
                    <input type="hidden" name="id" value="<?php echo $block->getOneTeam()->getId()?>" class="form-control">
                </div>
                <div class="form-group">
                    <small><?php echo __('name');?></small>
                    <input type="text" name="name" value="<?php echo $block->getOneTeam()->getName()?>" class="form-control">
                </div>
                <div class="form-group">
                    <small><?php echo __('country');?></small>
                    <input type="text" name="country" value="<?php echo $block->getOneTeam()->getCountry()?>" class="form-control">
                </div>
            </div>
            <div>
                <button type="submit" class="btn btn-primary"><?php echo __('Save-team');?></button>
                </form>
            </div>
        </div>
    </div>
</div>
