<?php
/**
 * @var \Study\Team\Block\Team $block
 */

?>

<h3><?php echo __('Teams');?></h3>

<a href="<?php echo $block->getUrl('*/*/add'); ?>"><?php echo __('Add new team');?></a>

<table>
    <thead>
    <th><?php echo __('id');?></th>
    <th><?php echo __('name');?></th>
    <th><?php echo __('country');?></th>
    <th><?php echo __('actions');?></th>
    </thead>
    <tbody>
    <tr>
        <?php foreach($block->getTeams() as $team):?>
        <td><?php echo $block->escapeHtml($team->getId()); ?></td>
        <td><?php echo $block->escapeHtml($team->getName()); ?></td>
        <td><?php echo $block->escapeHtml($team->getCountry()); ?></td>
        <td>
            <a href="<?php echo $block->getUrl('*/*/delete', ['id' => $team->getId()]) ?>"><?php echo __('DELETE');?></a>
            <a href="<?php echo $block->getUrl('*/*/edit', ['id' => $team->getId()]) ?>"><?php echo __('EDIT');?></a>
        </td>
    </tr>
    <?endforeach; ?>
    </tbody>
</table>

