<?php


namespace Study\Team\Model;


use Magento\Framework\Validation\ValidationException;

class Team extends \Magento\Framework\Model\AbstractModel implements \Magento\Framework\DataObject\IdentityInterface
{
    const CACHE_TAG = 'study_team_club';

    protected $_cacheTag = 'study_team_club';

    protected $_eventPrefix = 'study_team_club';

    protected function _construct()
    {
        $this->_init('Study\Team\Model\ResourceModel\Team');
    }

    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }

    public function getDefaultValues()
    {
        $values = [];

        return $values;
    }

    /**
     * @throws LocalizedException
     */
    protected function validate()
    {
        if (empty($this->getName())) {
            throw new ValidationException(__('Name is required field'));
        }
    }

    //  protected function _beforeLoad($modelId, $field = null)
    //  {
    //      return parent::_beforeLoad($modelId, $field); // TODO: Change the autogenerated stub
    //  }

    /**
     * @return Team
     * @throws LocalizedException
     */
    public function beforeSave()
    {
        $this->validate();
        return parent::beforeSave();
    }

    /*public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }*/

    /* public function afterDelete()
     {
         return parent::afterDelete(); // TODO: Change the autogenerated stub
     }*/
}
